kind: pipeline
type: ssh
name: default


server:
  host: ec2-3-20-232-197.us-east-2.compute.amazonaws.com
  user: ubuntu
  ssh_key:
    from_secret: Defaultkey.pem

steps:
- name: dev
  commands:
  - cd /home/ubuntu/calc-back
  - git pull origin master
  - npm i
  - npx knex migrate:latest
  - pm2 restart ecosystem.config.js