kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64
  
steps:
- name: dev
  commands:
  - apt update
  - apt install node
  - npm install -g pm2
  - pm2 start ecosystem.config.js