kind: pipeline
type: exec
name: default
  
steps:
- name: dev
  repo: calc_back
  commands:
  - curl -sL https://deb.nodesource.com/setup_14.x | bash -
  - apt-get install -y nodejs
  - npm install -g pm2
  - pm2 start ecosystem.config.js